# Generated by Django 6.0.4 on 2026-04-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'is_archived'], name='api_driver_status_2c08fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager')], default='PERSONNEL', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='api_user_role_36cef2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('unit_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('route', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('DISPATCHED', 'Dispatched'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('nullified_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'is_archived'], name='api_vehicle_status_9de6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['route', 'is_archived'], name='api_vehicle_route_21f689_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_verified'], name='api_ticket_status_68f259_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['issued_at', 'status'], name='api_ticket_issued__46b499_idx'),
        ),
    ]
